# Matrix Transposition

In this chapter, you will learn about matrix transposition. 

<br />

Transposition is another operation that can also be carried out on matrices. Just as when we transpose a vector, we transpose a matrix by taking each column in turn and making it a row. In other words, we interchange each column and row, so the first column becomes the first row, the second column becomes the second row, etc. For example,

$$
\mathbf{A} = \begin{bmatrix}
112 & 86 & 0 \\ 134 & 94 & 0
\end{bmatrix} \qquad 
\mathbf{A}^\intercal = \begin{bmatrix}
112 & 134 \\86 & 94 \\ 0 & 0
\end{bmatrix}
$$

Formally, if **A** is an $n \times k$ matrix with elements $a_{ij}$, then the transpose of **A**, denoted $\mathbf{A}^\intercal$ is a $k \times n$ matrix where element $a^\intercal_{ij}=a_{ji}$. Some properties of the matrix transpose are:

- $(\mathbf{A}^{\intercal}) ^{^{\intercal}} = \mathbf{A}$
- $(\lambda\mathbf{A})^{^{\intercal}} = \lambda \mathbf{A}^{\intercal}$ where $\lambda$ is a scalar
- $(\mathbf{A} + \mathbf{B})^{^{\intercal}} = \mathbf{A}^{\intercal} + \mathbf{B}^{\intercal}$ (This property extends to more than two matrices; $(\mathbf{A} + \mathbf{B} + \mathbf{C})^{^{\intercal}} = \mathbf{A}^{\intercal} + \mathbf{B}^{\intercal} + \mathbf{C}^{\intercal}$.)
- $(\mathbf{A}\mathbf{B})^{^{\intercal}} = \mathbf{B}^{\intercal} \mathbf{A}^{\intercal}$ (This property also extends to more than two matrices; $(\mathbf{A}\mathbf{B}\mathbf{C})^{^{\intercal}} = \mathbf{C}^{\intercal}\mathbf{B}^{\intercal} \mathbf{A}^{\intercal}$.)


Computationally, the `t()` function will produce the transpose of a matrix in R.

```{r}
# Create A
A = matrix(
  data = c(112, 134, 86, 94, 0, 0),
  nrow = 2
)

# Display A
A

# Compute transpose
t(A)
```


<br />






:::exercises
## Exercises

**Consider the following matrices:**

$$
\mathbf{A} = \begin{bmatrix}1 & 5 & -1 \\ 3 & 2 & -1 \\ 0 & 1 & 5 \end{bmatrix} \qquad \mathbf{B} = \begin{bmatrix}3 & 1 & 6 \\ 2 & 0 & 1 \\ -7 & -1 & 2 \end{bmatrix}
$$


1. Verify that $(\mathbf{A}+\mathbf{B})^\intercal = \mathbf{A}^\intercal + \mathbf{B}^\intercal$?

<button class="solution-btn solution-btn-default" onclick="toggle_visibility('solution_01');">Show/Hide Solution</button>
<div id="solution_01" style="display:none; margin: -40px 0 40px 40px;">

$$
\begin{split}
(\mathbf{A}+\mathbf{B})^\intercal &= \begin{bmatrix}4 & 6 & 5\\5 & 2 & 0\\ -7 & 0 & 7 \end{bmatrix}^\intercal = \begin{bmatrix}4 & 5 & -7\\6 & 2 & 0\\5 & 0& 7 \end{bmatrix} \\[3em]
\mathbf{A}^\intercal + \mathbf{B}^\intercal &= \begin{bmatrix}1 & 3 & 0\\5 & 2 & 1\\-1 & -1 & 5 \end{bmatrix} + \begin{bmatrix}3 & 2 & -7\\1 & 0 & -1\\6 & 1 & 2 \end{bmatrix} = \begin{bmatrix}4 & 5 & -7\\6 & 2 & 0\\5 & 0& 7 \end{bmatrix}
\end{split}
$$

</div>

2. Verify that $(\mathbf{A}\mathbf{B})^\intercal = \mathbf{B}^\intercal \mathbf{A}^\intercal$?.

<button class="solution-btn solution-btn-default" onclick="toggle_visibility('solution_02');">Show/Hide Solution</button>
<div id="solution_02" style="display:none; margin: -40px 0 40px 40px;">

$$
\begin{split}
(\mathbf{A}\mathbf{B})^\intercal &= \begin{bmatrix}20 & 2 & 9\\20 & 4 & 18\\-33 & -5 & 11 \end{bmatrix}^\intercal = \begin{bmatrix}20 & 20 & -33\\ 2 & 4& -5\\9 & 18 & 11 \end{bmatrix} \\[3em]
\mathbf{B}^\intercal \mathbf{A}^\intercal &= \begin{bmatrix}3 & 2 & -7\\1 & 0 & -1\\6 & 1 & 2 \end{bmatrix}\begin{bmatrix}1 & 3 & 0\\5 & 2 & 1\\-1 & -1 & 5 \end{bmatrix} = \begin{bmatrix}20 & 20 & -33\\ 2 & 4& -5\\9 & 18 & 11 \end{bmatrix}
\end{split}
$$

</div>



:::

<br />
