# (PART\*) Matrix Decomposition {-}


# Introduction to Matrix Decompostion

Matrix decomposition is a method of reducing or factoring a matrix into a set of product matrices. Another name for this is *matrix factorization*. Working with these product matrices often makes it easier to carry out more complex matrix operations (e.g., computing an inverse). 

In many ways, matrix decomposition is similar to factoring scalars. For example, we can factor the scalar 36 as:

$$
36 = 12 \times 3
$$

We could also have used the following factorizations:

$$
\begin{split}
36 &= 9 \times 4 \\[0.5em]
36 &= 18 \times 2 \\[0.5em]
36 &= 6 \times 3 \times 2 \\[0.5em]
36 &= 2 \times 2 \times 3 \times 3 \\[0.5em]
\end{split}
$$

There are potentially multiple ways to factor a scalar, and in different applications, some of these factorizations may prove more useful than others. For example, the last factorization in the example is referred to as the *prime factorization* (as the factors of 36 are all prime numbers) and is useful for some mathematical applications. 

The same is true of matrix decompoosition.

- There are many methods of matrix decomposition.
- Depending on the application, some of these methods are more useful than others.

In the following chapters, we will explore a few of the more common decomposition methods, including LU decomposition, QR decomposition, singular value decomposition, Cholsky decomposition, and eigen decomposition.


<br />
