--- 
title: "Matrix Algebra for Educational Scientists"
author: "Michael Rodriguez & Andrew Zieffler"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib, matrix-algebra-text.bib]
csl: "style/apa-single-spaced.csl"
link-citations: yes
github-repo: zief0002/matrix-algebra
description: "Matrix algebra content for QME students"
---


```{r book-setup, include=FALSE}
# Load libraries
library(knitr)
library(kableExtra)
library(patchwork)
library(tidyr)
library(tidyverse)


opts_knit$set(
  width = 85, 
  tibble.print_max = Inf
  )


# Set knitr options
opts_chunk$set(
  prompt = FALSE, 
  comment = NA, 
  message = FALSE, 
  warning = FALSE, 
  tidy = FALSE, 
  fig.align = 'center',
  out.width = '50%'
  )


# Set global options
options(htmltools.dir.version = FALSE)


# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```




# Foreword {-}

Spring 2021. 

The contents of this book constitute information from several set of notes from a variety of QME courses, including from an old course called EPsy 8269. We are making this book available as a resource for anyone who wants to use it. We will be adding and revising the content for awhile. Feel free to offer criticism, suggestion, and feedback. You can either [open an issue](https://github.com/zief0002/matrix-algebra/issues) on the book's github page or [send us an email](mailto: zief0002@umn.edu) directly.

<br />

Andrew Zieffler & Michael Rodriguez

zief0002@umn.edu


<br /> <br />


## Acknowledgments {-}

Many thanks to James Terwilliger, whose initial notes gave rise to some of this material. Also, thank you to all the students in our courses who have been through previous iterations of this material. Your feedback has been invaluable, and you are the world's greatest copy editors. 

<br /><br />


## Colophon {-}

<!-- Artwork by [&commat;allison_horst](https://twitter.com/allison_horst) -->

The book is typeset using [Karla](https://fonts.google.com/specimen/Karla) for the body font, [Lora](https://fonts.google.com/specimen/Lora) for the headings and [Sue Ellen Francisco](https://fonts.google.com/specimen/Sue+Ellen+Francisco) for the title. The color palette was generated using [coolors.co](https://coolors.co/).

Icon and note ideas and prototypes by [Desirée De Leon](http://desiree.rbind.io/).

Some of the book style and CSS code were inspired by: De Leon, D., &amp; Hill, A. (2019). [A handbook for teaching and learning with R and RStudio](https://rstudio4edu.github.io/rstudio4edu-book/).

<br /><br />




